version: 2
updates:
  # Maintain dependencies for cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/ion_derive/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/julia-semver/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
