[package]
name = "ion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"] }
dialoguer = "0.10.3"
dirs = "4.0.0"
env_logger = "0.10.0"
handlebars = "4.3.6"
log = "0.4.17"
node-semver = "2.1.0"
open = "3.2.0"
proc-macro2 = "1.0.50"
quote = "1.0.23"
serde = "1.0.152"
serde_derive = "1.0.152"
syn = "1.0.107"
toml = "0.5.10"
url = "2.3.1"
uuid = { version = "1.2.2", features = ["v4"] }
ion_derive = { path = "ion_derive" }
