[package]
name = "ion"
version = "0.1.0"
edition = "2021"
description = "a CLI toolbox for Julia developer"

[package.metadata.bundle]
identifier = "org.julialang.ion"
resources = ["resources/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ion"
path = "src/ion/lib.rs"

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"] }
dialoguer = "0.10.3"
dirs = "4.0.0"
env_logger = "0.10.0"
handlebars = "4.3.6"
log = "0.4.17"
node-semver = "2.1.0"
open = "3.2.0"
proc-macro2 = "1.0.50"
quote = "1.0.23"
serde = "1.0.152"
serde_derive = "1.0.152"
syn = "1.0.107"
toml = "0.5.10"
url = "2.2.2"
uuid = { version = "1.2.2", features = ["v4"] }
ion_derive = { version = "0.1.0", path = "ion_derive" }
octocrab = "0.18.1"
colorful = "0.2.2"

[build-dependencies]
copy_to_output = "2.0.0"
