[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
cargo_metadata = "0.18.0"
clap = "4.1.6"
semver = "1.0.16"
toml_edit = "0.19.3"
