name: Release

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  release:
    strategy:
      matrix:
        target:
        - aarch64-apple-darwin
        - x86_64-apple-darwin
        - x86_64-unknown-linux-musl
        include:
        - target: aarch64-apple-darwin
          os: macos-latest
          target_rustflags: ''
        - target: x86_64-apple-darwin
          os: macos-latest
          target_rustflags: ''
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          target_rustflags: ''

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        toolchain: stable

    - name: Install AArch64 Toolchain
      if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-aarch64-linux-gnu

    - name: Install ARM7 Toolchain
      if: ${{ matrix.target == 'armv7-unknown-linux-musleabihf' }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-linux-gnueabihf

    - name: Install linux openssl and Musl
      if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
      run: |
        sudo apt-get update
        sudo apt-get install musl-tools pkg-config libssl-dev

    - uses: taiki-e/install-action@just
    - name: Build ion ${{ matrix.target }}
      id: package
      run: |
        just build ${{ matrix.target }}
        just tarball ${{ matrix.target }}

    - name: Publish Archive
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        draft: false
        files: ${{ steps.package.outputs.archive }}
